import{useEffect,useState}from'react';import{AnimatePresence,motion}from'framer-motion';import{ArrowLeft,ArrowRight,Soup,Clock3,Expand,RotateCcw,StickyNote,Target,X}from'lucide-react';
type L='zh'|'en';type Pair=[string,string];const tx=(l:L,p:Pair)=>p[l==='zh'?0:1];
const titles:Pair[]=[['麻辣烫商家增长合作方案','Fantuan BD Case Study'],['客户背景','Merchant Background'],['顾问式销售流程','Consultative Sales Process'],['如何开始第一次会面','Opening the First Meeting'],['关键需求分析','Discovery Questions'],['重新设计外卖产品','Design a Delivery-Friendly Product'],['饭团如何帮助商家增长？','The Fantuan Value Proposition'],['合作方案比较','Partnership Package Comparison'],['为什么推荐VIP方案？','Why Recommend VIP?'],['不只看抽成，更要看实际利润','From Commission to Profitability'],['商家异议处理','Objection Handling'],['收入增长计划','Revenue Growth Plan'],['90天上线与增长计划','90-Day Launch Plan'],['如何衡量合作是否成功？','Measuring Partnership Success'],['推动签约与上线','Closing the Partnership'],['总结与下一步','Key Takeaways']];
const concerns:Pair[]=[['抽成会减少利润','Commission may reduce profit'],['称重模式难上线','Weight-based model'],['配送品质风险','Delivery quality'],['影响堂食运营','Kitchen disruption'],['增量客户不确定','Incremental demand']];
const obj=[['25%的抽成太高了。','25% commission is too high.','我理解您对抽成的顾虑。我们不能只看抽成比例，还要看这些订单是不是新增订单，以及扣除抽成、食材、包装和增量人工后，每单还能留下多少贡献利润。我们可以通过标准套餐、高毛利加购和可控活动来保护利润。','I understand. We should assess whether these orders are incremental and contribution-positive after fees, then protect margin with standardized combos and profitable add-ons.'],['麻辣烫是称重的，线上怎么卖？','How can weight-based malatang work online?','不复制称重模式：设计固定分量套餐，同时保留汤底、辣度和部分加料选择。','Use fixed-portion combos while keeping soup, spice and selected add-ons customizable.'],['配送后会不会漏汤？','Will delivery hurt quality?','上线前测试密封包装、配送时间和口感，必要时分装汤底。','Test sealed packaging, travel time and texture; separate broth if needed.'],['堂食已经很忙。','My kitchen is already busy.','在非高峰开放外卖，设置备餐时间并按产能控制订单。','Open off-peak, set prep times and control volume by capacity.'],['我已经在用 Uber Eats。','我已经在使用 Uber Eats。','饭团可以作为额外获客渠道，不必替代现有平台。','Fantuan can add a distinct acquisition channel without replacing existing platforms.'],['万一上线以后没有足够订单怎么办？','What if there are not enough orders?','不承诺订单量。先设定三个月试点，以曝光、转化、订单和贡献利润为指标；若表现不足，就优化菜单、图片、营业时段和活动后再复盘。','Use a measured pilot.'],['我不熟悉外卖平台，谁来帮助我运营？','Who will help me operate delivery?','我会协助完成菜单结构、图片描述、营业时间和上线设置，并在上线后按数据持续复盘；商家负责出品和现场执行，我们共同优化。','Fantuan supports onboarding and review.']];
function Card({children,onClick,on=false}:{children:any;onClick?:()=>void;on?:boolean}){return <motion.div whileHover={onClick?{y:-3}:undefined} onClick={onClick} className={'card '+(onClick?'click ':'')+(on?'on':'')}>{children}</motion.div>};
function Title({n,l}:{n:number;l:L}){return <><div className="kicker">饭团 · 商家增长合作提案</div><h1>{tx(l,titles[n])}</h1></>}
function Choice({label,value,set,items}:{label:string;value:string;set:(v:string)=>void;items:string[]}){return <label className="choice">{label}<span>{items.map(x=><button className={value===x?'picked':''} onClick={()=>set(x)} key={x}>{x}</button>)}</span></label>}
function merchantProfile(priority:string,capacity:string,experience:string){
 const constrained=capacity==='有限',ready=capacity==='充足',novice=experience==='无经验',expert=experience==='经验丰富';
 if(priority==='利润优先'&&constrained)return{type:'谨慎控本型商家',summary:'李先生高度关注单笔利润，且后厨余量有限。合作必须先证明“每一单有利润”，并避免外卖干扰堂食。',risk:'主要风险：抽成敏感、爆单导致出餐失控。',plan:'建议策略：少量标准套餐＋非高峰限时开放＋每日订单上限，先用利润计算器确认贡献利润。'};
 if(priority==='利润优先'&&ready)return{type:'利润效率型商家',summary:'李先生以利润为第一目标，同时具备承接增量订单的产能，适合用标准化套餐提升单位时间产出。',risk:'主要风险：活动力度过大，订单增长但贡献利润下降。',plan:'建议策略：VIP方案小范围试点＋高毛利加购＋按周复盘客单价与预计单笔贡献利润。'};
 if(priority==='曝光优先'&&constrained)return{type:'品牌起步但产能受限型',summary:'李先生需要新品牌曝光，但后厨暂时无法承接大规模订单。应把曝光转化为可控的新客，而不是追求短期爆量。',risk:'主要风险：活动带来集中订单，损害堂食和评分。',plan:'建议策略：限定配送时段与半径＋控制活动库存＋先优化页面转化，再逐步放量。'};
 if(priority==='曝光优先'&&ready)return{type:'新品牌增长型商家',summary:'李先生希望快速建立本地知名度，并且后厨有充足余量，是最适合通过平台曝光获取增量客户的组合。',risk:'主要风险：只看订单量，忽略复购与利润质量。',plan:'建议策略：VIP方案的额外曝光＋新店活动＋双人/家庭套餐，同时追踪新客、复购率和贡献利润。'};
 if(priority==='扩店验证'&&constrained)return{type:'谨慎试点型连锁候选',summary:'李先生想为未来扩店验证市场，但当前首店产能有限。第一阶段重点应是收集高质量数据，而不是扩大订单规模。',risk:'主要风险：样本过少或运营波动导致错误的扩店判断。',plan:'建议策略：三个月受控试点，固定菜单和营业时段，重点观察订单区域、热门产品与复购。'};
 if(priority==='扩店验证'&&ready&&expert)return{type:'可复制扩张型商家',summary:'李先生目标明确、产能充足且熟悉平台运营，具备测试多店复制模型的条件。',risk:'主要风险：过早投入高成本曝光，尚未验证单店模型。',plan:'建议策略：先用VIP方案验证产品与区域数据，达到利润和复购标准后再评估至尊方案。'};
 const experienceNote=novice?'需要饭团提供更完整的菜单、上线和数据复盘支持。':expert?'可让商家承担更多日常运营，由市场开发代表聚焦增长与扩店数据。':'需要共同制定运营节奏并定期复盘。';
 return{type:priority==='扩店验证'?'数据验证型商家':'稳健成长型商家',summary:`李先生目前以${priority}为核心，后厨产能${capacity}，外卖经验${experience}。${experienceNote}`,risk:'主要风险：目标、产能与平台投入不匹配。',plan:'建议策略：从可控的VIP方案试点开始，用利润、产能和客户数据决定下一阶段投入。'};
}
export default function App(){const[l]=useState<L>('zh'),[n,setN]=useState(0),[sec,setSec]=useState(0),[notes,setNotes]=useState(false),[present,setPresent]=useState(false);useEffect(()=>{const id=setInterval(()=>setSec(x=>x+1),1000);return()=>clearInterval(id)},[]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')setN(x=>Math.min(15,x+1));if(e.key==='ArrowLeft')setN(x=>Math.max(0,x-1))};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);const go=(x:number)=>{setN(Math.max(0,Math.min(15,x)));setNotes(false)};return <main className={present?'present':''}><header><button className="brand" onClick={()=>go(0)}><i><Soup/></i>饭团 <b>商家合作提案</b></button><nav>{titles.map((x,i)=><button className={i===n?'on':''} onClick={()=>go(i)} key={i}>{i+1}</button>)}</nav><div className="tools"><button onClick={()=>setPresent(!present)}><Target/>{tx(l,['演讲模式','Present'])}</button><button onClick={()=>document.documentElement.requestFullscreen?.()}><Expand/></button></div></header><section className="stage"><div className="counter">{String(n+1).padStart(2,'0')} / 16　{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</div><AnimatePresence mode="wait"><motion.article key={n+'-'+l} initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-25}}>{slide(n,l,go)}</motion.article></AnimatePresence></section><footer><button disabled={!n} onClick={()=>go(n-1)}><ArrowLeft/>{tx(l,['上一页','Previous'])}</button><div className="progress"><i style={{width:`${(n+1)/16*100}%`}}/></div><button onClick={()=>setNotes(!notes)}><StickyNote/>{tx(l,['讲者备注','Notes'])}</button><button onClick={()=>{go(0);setSec(0)}}><RotateCcw/>{tx(l,['重置','Reset'])}</button><button disabled={n===15} onClick={()=>go(n+1)}>{tx(l,['下一页','Next'])}<ArrowRight/></button></footer>{notes&&<aside><button onClick={()=>setNotes(false)}><X/></button><h3>{tx(l,['讲者备注','Presenter Notes'])}</h3><p>{tx(l,[`主旨：${titles[n][0]}。自然表达：让我们从商家的真实经营情况出发。建议转场：接下来我们看如何把这个判断落到可执行方案。可能追问：如何验证这个判断？`,`Message: ${titles[n][1]}. Natural line: Let’s start with the merchant’s operating reality. Transition: Now let’s turn this insight into action. Likely follow-up: How would you validate the assumption?`])}</p></aside>}</main>}
function slide(n:number,l:L,go:(x:number)=>void){switch(n){case 0:return <div className="cover"><div className="steam">〰　〰　〰</div><Soup className="hero-icon"/><div className="kicker">饭团 · 商家增长合作提案</div><h1>{tx(l,titles[0])}</h1><p>{tx(l,['帮助一家新开的麻辣烫店建立可盈利、可复制的外卖增长模式','Building a Profitable and Scalable Delivery Strategy for a New Malatang Restaurant'])}</p><b>Chris Yang　<span>饭团市场开发代表</span></b><button className="primary" onClick={()=>go(1)}>{tx(l,['开始提案','Start Presentation'])}<ArrowRight/></button></div>;case 1:return <Merchant l={l}/>;case 2:return <Process l={l}/>;case 3:return <Opening l={l}/>;case 4:return <Discovery l={l}/>;case 5:return <Combo l={l}/>;case 6:return <Values l={l}/>;case 7:return <Packages l={l}/>;case 8:return <Recommend l={l}/>;case 9:return <Calc l={l}/>;case 10:return <Objections l={l}/>;case 11:return <Growth l={l}/>;case 12:return <Timeline l={l}/>;case 13:return <Dashboard l={l}/>;case 14:return <Closing l={l} go={go}/>;default:return <div><Title n={15} l={l}/><div className="four">{([['先理解商家，再推荐方案。','Understand before recommending.'],['为外卖设计产品。','Design the product for delivery.'],['讨论增量利润，而不只抽成。','Discuss incremental profit, not only commission.'],['签约是长期合作的开始。','Signing begins the partnership.']] as Pair[]).map((x,i)=><Card key={i}><em>0{i+1}</em><h2>{tx(l,x)}</h2></Card>)}</div><blockquote>{tx(l,['合作原则：不追求向商家销售最贵的方案，而是选择最符合当前发展阶段、能够带来可持续增长的方案。','A strong BD professional helps the merchant choose the growth strategy that best fits their current stage.'])}</blockquote><div className="final-close"><b>建议下一步</b><span>确认试点目标 → 准备菜单与图片 → 完成签约上线 → 按周复盘优化</span><strong>感谢聆听 · 欢迎提问</strong></div></div>}}
function Merchant({l}:{l:L}){const[a,setA]=useState(0);return <div><Title n={1} l={l}/><div className="two"><Card><div className="avatar">李</div><h2>{l==='zh'?'李先生':'Mr. Li'}</h2><p>{tx(l,['8年餐饮经验 · 首家自有品牌 · 主要决策者','8 years in restaurants · First owned brand · Key decision-maker'])}</p><div className="tags"><b>{tx(l,['价格敏感','Margin-aware'])}</b><b>{tx(l,['计划扩店','Expansion-minded'])}</b><b>{tx(l,['外卖新手','Delivery novice'])}</b></div></Card><div className="concerns">{concerns.map((x,i)=><Card key={i} onClick={()=>setA(i)} on={a===i}><b>{tx(l,x)}</b>{a===i&&<><p>{tx(l,['为什么重要：它直接影响签约信心与长期留存。','Why it matters: it affects confidence and retention.'])}</p><small>{['计算真实贡献利润','设计固定分量套餐','测试密封包装','控制时段与订单量','设定三个月关键指标'][i]}</small></>}</Card>)}</div></div></div>}
function Process({l}:{l:L}){const[a,setA]=useState(0),it=['门店调研','建立信任','需求诊断','方案设计','处理异议','签约与跟进'];return <div><Title n={2} l={l}/><div className="six">{it.map((x,i)=><Card key={x} onClick={()=>setA(i)} on={a===i}><em>0{i+1}</em><h3>{x}</h3>{a===i&&<p>{tx(l,['先理解商家，再进入下一步。','A merchant-first, evidence-based step.'])}</p>}</Card>)}</div><blockquote>{tx(l,['我不会先卖套餐，而是先确认饭团是否真的能帮助商家赚钱。','I would first determine how Fantuan can genuinely help the merchant grow.'])}</blockquote></div>}
function Opening({l}:{l:L}){const[step,setStep]=useState(0),[bad,setBad]=useState(false);const conversation=[
 {who:'Chris',text:'李老板您好，我是饭团的 Chris。谢谢您在开业这么忙的时候抽时间见我。先恭喜您终于把自己的麻辣烫品牌开起来了。'},
 {who:'李先生',text:'谢谢。最近确实挺忙的，你们主要是想让我上平台吧？'},
 {who:'Chris',text:'是的，不过我今天不想一上来就谈套餐和抽成。我了解到您做了八年餐饮，从后厨、成本到门店管理都很熟，而且以后还想在大温继续开店。这次自己做品牌，您最想先把哪件事做好？'},
 {who:'李先生',text:'第一家店还是要先稳住利润，也想看看这个品牌在不同区域有没有市场。'},
 {who:'Chris',text:'明白，所以重点不是单纯增加订单，而是增加有利润、后厨接得住的订单，同时为以后扩店积累数据。这样吧，我先用几分钟了解您的客单价、忙闲时段和产能，再判断饭团适不适合；如果不适合，我也会直接告诉您。可以吗？'}
 ];const reasons=['礼貌说明身份，尊重商家的时间，先建立正常的人际交流。','商家直接试探销售目的，此时不回避，但也不急着报价。','用事前调研肯定对方经验，再用开放式问题让商家先谈目标。','复述商家的原话，确认“利润＋扩店验证”才是真正需求。','总结共同目标、降低销售戒备，并获得继续提问的许可。'];return <div><Title n={3} l={l}/><div className="two opening"><div className="chat">{conversation.slice(0,step+1).map((m,i)=><motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} key={i} className={'bubble '+(m.who==='Chris'?'me':'')}><b>{m.who}</b><p>{m.text}</p></motion.div>)}</div><Card><div className="profile-label">第 {step+1} 步 · 开场目的</div><h2>{['礼貌破冰','回应商家试探','认可经历并提问','确认真实目标','获得访谈许可'][step]}</h2><p>{reasons[step]}</p><hr/><h3>本步沟通重点</h3><p>{['尊重商家时间，建立平等的沟通关系','坦诚说明来意，不回避合作目的','用事前调研建立信任，用开放式问题了解目标','准确倾听并复述，确认核心需求','降低戒备，在获得许可后进入需求访谈'][step]}</p>{bad&&<div className="bubble bad"><b>价格先行的开场方式</b><p>“李老板，我们有20%、25%和30%三档方案，VIP曝光最好，今天可以签吗？”</p><small>问题：还没了解经营目标就开始报价，容易让商家只关注抽成并产生防备。</small></div>}</Card></div><div className="actions"><button className="primary" onClick={()=>setStep(s=>Math.min(4,s+1))}>{step<4?'继续对话':'已进入需求访谈'}</button><button onClick={()=>{setStep(0);setBad(false)}}>从头查看</button><button onClick={()=>setBad(!bad)}>{bad?'隐藏价格先行风险':'对比价格先行方式'}</button></div></div>}
function Discovery({l}:{l:L}){const[p,setP]=useState('利润优先'),[c,setC]=useState('适中'),[e,setE]=useState('无经验');return <div><Title n={4} l={l}/><div className="two"><div className="questions">{['经营模式','客户需求','后厨产能','业务目标','成功标准'].map((x,i)=><Card key={x}><b>0{i+1} · {x}</b><p>{['堂食、自取或外卖？称重或套餐？客单价？','热门汤底与食材？主要客户是谁？','高峰与空闲时段？额外产能？','新客、空闲利用，还是扩店验证？','三个月后什么结果代表成功？'][i]}</p></Card>)}</div><Card><Choice label="首要目标" value={p} set={setP} items={['利润优先','曝光优先','扩店验证']}/><Choice label="后厨剩余产能" value={c} set={setC} items={['有限','适中','充足']}/><Choice label="外卖经验" value={e} set={setE} items={['无经验','有一些','经验丰富']}/><hr/><div className="profile-label">动态商家画像</div><h2>{merchantProfile(p,c,e).type}</h2><p>{merchantProfile(p,c,e).summary}</p><div className="profile-risk">{merchantProfile(p,c,e).risk}</div><div className="profile-plan">{merchantProfile(p,c,e).plan}</div></Card></div></div>}
function Combo({l}:{l:L}){const[b,setB]=useState(16.9),[add,setAdd]=useState('不选'),[drink,set饮料]=useState('不选');return <div><Title n={5} l={l}/><div className="transform">自选 → 称重 → 汤底　<ArrowRight/>　<b>标准套餐 → 汤底 → 辣度 → 加购 → 配送</b></div><div className="two"><div className="menu">{[['经典单人',16.9],['高蛋白牛肉',20.9],['素菜套餐',15.9],['双人分享',32.9],['家庭套餐',49.9],['夜宵套餐',18.9]].map(x=><Card key={x[0]} onClick={()=>setB(x[1] as number)} on={b===x[1]}><b>{x[0]}</b><h3>${x[1]}</h3></Card>)}</div><Card><h2>搭配一份外卖套餐</h2><Choice label="高利润加购" value={add} set={setAdd} items={['不选','肥牛 +$4']}/><Choice label="饮料选择" value={drink} set={set饮料} items={['不选','饮料 +$2.5']}/><div className="result">${(b+(add==='不选'?0:4)+(drink==='不选'?0:2.5)).toFixed(2)}</div><small>{tx(l,['示例假设价格','Sample assumptions'])}</small></Card></div></div>}
function Values({l}:{l:L}){return <div><Title n={6} l={l}/><div className="five">{([['新客获取','New Customers'],['增量收入','Incremental Revenue'],['更高客单','Higher AOV'],['运营支持','Operational Support'],['扩店数据','Expansion Data']] as Pair[]).map(x=><Card key={x[0]}><Target/><h2>{tx(l,x)}</h2><p>{tx(l,['围绕当前阶段，建立可衡量的增长渠道。','Build a measurable channel for the current stage.'])}</p></Card>)}</div><blockquote>{tx(l,['饭团不是简单增加一个订单入口，而是帮助商家建立新的获客和增长渠道。','Fantuan is not just another order入口—it is a customer acquisition and growth channel.'])}</blockquote></div>}
function Packages({l}:{l:L}){return <div><Title n={7} l={l}/><div className="three">{[['20%','经济方案','基础排序展示 · 基础配送'],['25%','VIP方案','额外曝光 · 活动支持 · 宣传物料'],['30%','至尊方案','稳定高等级曝光 · 更高力度支持']].map((x,i)=><Card key={x[0]} on={i===1}>{i===1&&<mark>推荐方案</mark>}<h2>{x[1]}</h2><div className="result">{x[0]}</div><p>{x[2]}</p><small>{['成熟商家 / 低成本优先','新品牌 / 平衡成本与增长','激进增长 / 产能成熟'][i]}</small></Card>)}</div><p className="legal">{tx(l,['具体权益、费用和平台规则以饭团正式合同及当前政策为准。','Final benefits, commission terms and policies are subject to Fantuan’s official agreement and current policies.'])}</p></div>}
function Recommend({l}:{l:L}){const[sel,setSel]=useState(['建立知名度','测试需求']),it=['降低成本','建立知名度','增加订单','测试需求','多店扩张','保护产能'];const r=sel.includes('降低成本')&&sel.length<3?'20% 经济方案':sel.length>4?'30% 至尊方案':'25% VIP方案';return <div><Title n={8} l={l}/><div className="two recommend"><div>{it.map(x=><button className={sel.includes(x)?'picked':''} onClick={()=>setSel(s=>s.includes(x)?s.filter(y=>y!==x):[...s,x])}>{x}</button>)}</div><Card><small>推荐方案</small><div className="result">{r}</div><p>{tx(l,['新品牌需要曝光，同时要控制早期测试压力；VIP在成本与增长之间提供平衡。','A new brand needs visibility while controlling early pressure. VIP balances cost and growth.'])}</p></Card></div><blockquote>{tx(l,['我推荐VIP，不是因为它抽成更高，而是因为它更符合商家当前的发展阶段。','I recommend VIP because it best matches the merchant’s current stage—not because its commission is higher.'])}</blockquote></div>}
function Calc({l}:{l:L}){const[a,setA]=useState(24),[food,setFood]=useState(30),[comm,setComm]=useState(25),[orders,set订单量]=useState(15);const c=a*(1-comm/100)-a*food/100-1.2-2,m=c*orders*26;return <div><Title n={9} l={l}/><div className="two calc"><div>{[['平均客单价',a,setA,12,50],['食材成本率 %',food,setFood,15,50],['平台抽成 %',comm,setComm,20,30],['预计饭团日均新增订单（单/天）',orders,set订单量,1,60]].map(([x,v,s,min,max]:any)=><label>{x}<b>{x==='预计饭团日均新增订单（单/天）'?v+' 单':x.includes('%')?v+'%':'$'+v}</b><input type="range" value={v} min={min} max={max} onChange={e=>s(+e.target.value)}/></label>)}</div><Card><small>预计单笔贡献利润</small><div className="result">${c.toFixed(2)}</div><small>预计月度增量贡献利润</small><div className="result teal">${m.toFixed(0)}</div><p>{tx(l,['以上为基于示例假设的简化测算，不代表平台承诺。按每月营业26天计算，未计入房租等固定成本、税费、活动补贴、退款及其他费用。','Simplified estimate, not guaranteed. Excludes fixed costs, tax, promotions and refunds.'])}</p></Card></div></div>}
function Objections({l}:{l:L}){const[a,setA]=useState(0),[show,setShow]=useState(false);return <div><Title n={10} l={l}/><div className="two objection"><div>{obj.map((x,i)=><button className={a===i?'picked':''} onClick={()=>{setA(i);setShow(false)}}>{x[l==='zh'?0:1]}</button>)}</div><Card><h2>“{obj[a][l==='zh'?0:1]}”</h2>{show?<><p>{obj[a][l==='zh'?2:3]}</p><small>✓ 认可顾虑　✓ 追问原因　✓ 解释价值　✓ 提供方案　✓ 推动下一步</small></>:<button className="primary" onClick={()=>setShow(true)}>{tx(l,['显示建议回答','Reveal Suggested Answer'])}</button>}</Card></div></div>}
function Growth({l}:{l:L}){const[a,setA]=useState(0),it=['新客获取','菜单优化','提高客单价','利用非高峰','发展自取','评价与复购'];return <div><Title n={11} l={l}/><div className="two growth"><div>{it.map((x,i)=><button className={a===i?'picked':''} onClick={()=>setA(i)}>{i+1}<span>{x}</span></button>)}</div><Card><small>建议动作</small><h2>{it[a]}</h2><p>{tx(l,['采取小步、可测试的运营动作，并持续复盘结果。','Use small, testable actions and review results continuously.'])}</p><hr/><b>衡量指标 → {['列表曝光量','菜单浏览转化率','平均客单价','分时段订单量','自取订单占比','评分与复购率'][a]}</b></Card></div></div>}
function Timeline({l}:{l:L}){return <div><Title n={12} l={l}/><div className="four timeline">{[['第1–2周','设置与验证','确定套餐、测试包装、准备图片、设置营业时间'],['第3–4周','小范围上线','控制订单量、记录备餐时间、解决包装与出品问题'],['第2个月','增长优化','测试合适的活动、加购、双人套餐和自取需求'],['第3个月','复盘与扩张','复盘订单量、客单价、贡献利润、评价和订单区域']].map((x,i)=><Card><em>0{i+1} · {x[0]}</em><h2>{x[1]}</h2><p>{l==='zh'?x[2]:'Validate, launch carefully, optimize and decide how to scale.'}</p></Card>)}</div></div>}
function Dashboard({l}:{l:L}){const[p,setP]=useState(1),d=[[1200,42,3.5,26],[4600,210,4.6,27],[14800,790,5.3,29]][p];return <div><Title n={13} l={l}/><div className="tabs">{['第1周','第1个月','第3个月'].map((x,i)=><button className={p===i?'picked':''} onClick={()=>setP(i)}>{x}</button>)}</div><div className="four dashboard">{[['列表曝光量',d[0]],['订单量',d[1]],['下单转化率',d[2]+'%'],['平均客单价','$'+d[3]],['顾客评分','4.8 / 5'],['平均备餐时间','18分钟'],['复购率','22%'],['投诉率','1.2%']].map(x=><Card><small>{x[0]}</small><div className="metric">{x[1]}</div><b>示例数据</b></Card>)}</div></div>}
function Closing({l,go}:{l:L;go:(x:number)=>void}){return <div><Title n={14} l={l}/><div className="two close-sale"><Card><h3>{tx(l,['商家目标','Merchant Goals'])}</h3><p>获取新客 · 利用非高峰产能 · 保护利润 · 为扩店验证市场</p><h3>{tx(l,['建议方案','Recommended Solution'])}</h3><p>标准化外卖菜单 · 25% VIP方案 · 三个月可控试点 · 按数据持续优化</p></Card><Card><p>{tx(l,['李老板，我建议从VIP方案和标准化外卖套餐开始，设定三个月测试目标。如果您认可，下一步准备菜单、图片和营业时间。您觉得怎么样？','Mr. Li, I recommend VIP, a standardized menu and a three-month pilot. If this makes sense, our next step is to prepare the menu, photos and hours. How does that sound?'])}</p><button className="primary">{tx(l,['我愿意推进','Proceed to Onboarding'])}</button><button onClick={()=>go(9)}>{tx(l,['我还要考虑抽成','Return to Profit Calculator'])}</button><button onClick={()=>go(12)}>{tx(l,['了解运营细节','View 90-Day Plan'])}</button></Card></div></div>}