import{useEffect,useState}from'react';import{AnimatePresence,motion}from'framer-motion';import{ArrowLeft,ArrowRight,Soup,Clock3,Expand,RotateCcw,StickyNote,Target,X}from'lucide-react';
type L='zh'|'en';type Pair=[string,string];const tx=(l:L,p:Pair)=>p[l==='zh'?0:1];
const titles:Pair[]=[['麻辣烫商家增长合作方案','Fantuan BD Case Study'],['客户背景','Merchant Background'],['顾问式销售流程','Consultative Sales Process'],['如何开始第一次会面','Opening the First Meeting'],['关键需求分析','Discovery Questions'],['重新设计外卖产品','Design a Delivery-Friendly Product'],['平台规模与合作依据','The Fantuan Value Proposition'],['不只看抽成，更要看实际利润','From Commission to Profitability'],['合作方案比较','Partnership Package Comparison'],['根据商家需求推荐方案','Why Recommend VIP?'],['商家异议处理','Objection Handling'],['收入增长计划','Revenue Growth Plan'],['90天上线与增长计划','90-Day Launch Plan'],['如何衡量合作是否成功？','Measuring Partnership Success'],['推动签约与上线','Closing the Partnership'],['总结与下一步','Key Takeaways']];
const concerns:Pair[]=[['抽成会减少利润','Commission may reduce profit'],['称重模式难上线','Weight-based model'],['配送品质风险','Delivery quality'],['影响堂食运营','Kitchen disruption'],['增量客户不确定','Incremental demand']];
const obj=[['25%的抽成太高了。','25% commission is too high.','我理解您对抽成的顾虑。我们不能只看抽成比例，还要看这些订单是不是新增订单，以及扣除抽成、食材、包装和增量人工后，每单还能留下多少贡献利润。我们可以通过标准套餐、高毛利加购和可控活动来保护利润。','I understand. We should assess whether these orders are incremental and contribution-positive after fees, then protect margin with standardized combos and profitable add-ons.'],['麻辣烫是称重的，线上怎么卖？','How can weight-based malatang work online?','不复制称重模式：设计固定分量套餐，同时保留汤底、辣度和部分加料选择。','Use fixed-portion combos while keeping soup, spice and selected add-ons customizable.'],['配送后会不会漏汤？','Will delivery hurt quality?','上线前测试密封包装、配送时间和口感，必要时分装汤底。','Test sealed packaging, travel time and texture; separate broth if needed.'],['堂食已经很忙。','My kitchen is already busy.','在非高峰开放外卖，设置备餐时间并按产能控制订单。','Open off-peak, set prep times and control volume by capacity.'],['我已经在用 Uber Eats。','我已经在使用 Uber Eats。','饭团可以作为额外获客渠道，不必替代现有平台。','Fantuan can add a distinct acquisition channel without replacing existing platforms.'],['万一上线以后没有足够订单怎么办？','What if there are not enough orders?','不承诺订单量。先设定三个月试点，以曝光、转化、订单和贡献利润为指标；若表现不足，就优化菜单、图片、营业时段和活动后再复盘。','Use a measured pilot.'],['我不熟悉外卖平台，谁来帮助我运营？','Who will help me operate delivery?','我会协助完成菜单结构、图片描述、营业时间和上线设置，并在上线后按数据持续复盘；商家负责出品和现场执行，我们共同优化。','Fantuan supports onboarding and review.']];
function Card({children,onClick,on=false}:{children:any;onClick?:()=>void;on?:boolean}){return <motion.div whileHover={onClick?{y:-3}:undefined} onClick={onClick} className={'card '+(onClick?'click ':'')+(on?'on':'')}>{children}</motion.div>};
function Title({n,l}:{n:number;l:L}){return <><div className="kicker">饭团 · 商家增长合作提案</div><h1>{tx(l,titles[n])}</h1></>}
function Choice({label,value,set,items}:{label:string;value:string;set:(v:string)=>void;items:string[]}){return <label className="choice">{label}<span>{items.map(x=><button className={value===x?'picked':''} onClick={()=>set(x)} key={x}>{x}</button>)}</span></label>}
function merchantProfile(priority:string,capacity:string,experience:string){
 const constrained=capacity==='有限',ready=capacity==='充足',novice=experience==='无经验',expert=experience==='经验丰富';
 if(priority==='利润优先'&&constrained)return{type:'谨慎控本型商家',summary:'李先生高度关注单笔利润，且后厨余量有限。合作必须先证明“每一单有利润”，并避免外卖干扰堂食。',risk:'主要风险：抽成敏感、爆单导致出餐失控。',plan:'建议策略：少量标准套餐＋非高峰限时开放＋每日订单上限，先用利润计算器确认贡献利润。'};
 if(priority==='利润优先'&&ready)return{type:'利润效率型商家',summary:'李先生以利润为第一目标，同时具备承接增量订单的产能，适合用标准化套餐提升单位时间产出。',risk:'主要风险：活动力度过大，订单增长但贡献利润下降。',plan:'建议策略：VIP方案小范围试点＋高毛利加购＋按周复盘客单价与预计单笔贡献利润。'};
 if(priority==='曝光优先'&&constrained)return{type:'品牌起步但产能受限型',summary:'李先生需要新品牌曝光，但后厨暂时无法承接大规模订单。应把曝光转化为可控的新客，而不是追求短期爆量。',risk:'主要风险：活动带来集中订单，损害堂食和评分。',plan:'建议策略：限定配送时段与半径＋控制活动库存＋先优化页面转化，再逐步放量。'};
 if(priority==='曝光优先'&&ready)return{type:'新品牌增长型商家',summary:'李先生希望快速建立本地知名度，并且后厨有充足余量，是最适合通过平台曝光获取增量客户的组合。',risk:'主要风险：只看订单量，忽略复购与利润质量。',plan:'建议策略：VIP方案的额外曝光＋新店活动＋双人/家庭套餐，同时追踪新客、复购率和贡献利润。'};
 if(priority==='扩店验证'&&constrained)return{type:'谨慎试点型连锁候选',summary:'李先生想为未来扩店验证市场，但当前首店产能有限。第一阶段重点应是收集高质量数据，而不是扩大订单规模。',risk:'主要风险：样本过少或运营波动导致错误的扩店判断。',plan:'建议策略：三个月受控试点，固定菜单和营业时段，重点观察订单区域、热门产品与复购。'};
 if(priority==='扩店验证'&&ready&&expert)return{type:'可复制扩张型商家',summary:'李先生目标明确、产能充足且熟悉平台运营，具备测试多店复制模型的条件。',risk:'主要风险：过早投入高成本曝光，尚未验证单店模型。',plan:'建议策略：先用VIP方案验证产品与区域数据，达到利润和复购标准后再评估至尊方案。'};
 const experienceNote=novice?'需要饭团提供更完整的菜单、上线和数据复盘支持。':expert?'可让商家承担更多日常运营，由市场开发代表聚焦增长与扩店数据。':'需要共同制定运营节奏并定期复盘。';
 return{type:priority==='扩店验证'?'数据验证型商家':'稳健成长型商家',summary:`李先生目前以${priority}为核心，后厨产能${capacity}，外卖经验${experience}。${experienceNote}`,risk:'主要风险：目标、产能与平台投入不匹配。',plan:'建议策略：从可控的VIP方案试点开始，用利润、产能和客户数据决定下一阶段投入。'};
}
export default function App(){const[l]=useState<L>('zh'),[n,setN]=useState(0),[sec,setSec]=useState(0),[notes,setNotes]=useState(false),[present,setPresent]=useState(false);useEffect(()=>{const id=setInterval(()=>setSec(x=>x+1),1000);return()=>clearInterval(id)},[]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')setN(x=>Math.min(15,x+1));if(e.key==='ArrowLeft')setN(x=>Math.max(0,x-1))};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);const go=(x:number)=>{setN(Math.max(0,Math.min(15,x)));setNotes(false)};return <main className={present?'present':''}><header><button className="brand" onClick={()=>go(0)}><i><Soup/></i>饭团 <b>商家合作提案</b></button><nav>{titles.map((x,i)=><button className={i===n?'on':''} onClick={()=>go(i)} key={i}>{i+1}</button>)}</nav><div className="tools"><button onClick={()=>setPresent(!present)}><Target/>{tx(l,['演讲模式','Present'])}</button><button onClick={()=>document.documentElement.requestFullscreen?.()}><Expand/></button></div></header><section className="stage"><div className="counter">{String(n+1).padStart(2,'0')} / 16　{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</div><AnimatePresence mode="wait"><motion.article key={n+'-'+l} initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-25}}>{slide(n,l,go)}</motion.article></AnimatePresence></section><footer><button disabled={!n} onClick={()=>go(n-1)}><ArrowLeft/>{tx(l,['上一页','Previous'])}</button><div className="progress"><i style={{width:`${(n+1)/16*100}%`}}/></div><button onClick={()=>setNotes(!notes)}><StickyNote/>{tx(l,['讲者备注','Notes'])}</button><button onClick={()=>{go(0);setSec(0)}}><RotateCcw/>{tx(l,['重置','Reset'])}</button><button disabled={n===15} onClick={()=>go(n+1)}>{tx(l,['下一页','Next'])}<ArrowRight/></button></footer>{notes&&<aside><button onClick={()=>setNotes(false)}><X/></button><h3>{tx(l,['讲者备注','Presenter Notes'])}</h3><p>{tx(l,[`主旨：${titles[n][0]}。自然表达：让我们从商家的真实经营情况出发。建议转场：接下来我们看如何把这个判断落到可执行方案。可能追问：如何验证这个判断？`,`Message: ${titles[n][1]}. Natural line: Let’s start with the merchant’s operating reality. Transition: Now let’s turn this insight into action. Likely follow-up: How would you validate the assumption?`])}</p></aside>}</main>}
function slide(n:number,l:L,go:(x:number)=>void){switch(n){case 0:return <div className="cover"><div className="steam">〰　〰　〰</div><Soup className="hero-icon"/><div className="kicker">饭团 · 商家增长合作提案</div><h1>{tx(l,titles[0])}</h1><p>{tx(l,['帮助一家新开的麻辣烫店建立可盈利、可复制的外卖增长模式','Building a Profitable and Scalable Delivery Strategy for a New Malatang Restaurant'])}</p><b>Chris Yang　<span>饭团市场开发代表</span></b><button className="primary" onClick={()=>go(1)}>{tx(l,['开始提案','Start Presentation'])}<ArrowRight/></button></div>;case 1:return <Merchant l={l}/>;case 2:return <Process l={l}/>;case 3:return <Opening l={l}/>;case 4:return <Discovery l={l}/>;case 5:return <Combo l={l}/>;case 6:return <Values l={l}/>;case 7:return <Calc l={l}/>;case 8:return <Packages l={l}/>;case 9:return <Recommend l={l}/>;case 10:return <Objections l={l}/>;case 11:return <Growth l={l}/>;case 12:return <Timeline l={l}/>;case 13:return <Dashboard l={l}/>;case 14:return <Closing l={l} go={go}/>;default:return <div><Title n={15} l={l}/><div className="four">{([['先理解商家，再推荐方案。','Understand before recommending.'],['为外卖设计产品。','Design the product for delivery.'],['讨论增量利润，而不只抽成。','Discuss incremental profit, not only commission.'],['签约是长期合作的开始。','Signing begins the partnership.']] as Pair[]).map((x,i)=><Card key={i}><em>0{i+1}</em><h2>{tx(l,x)}</h2></Card>)}</div><blockquote>{tx(l,['合作原则：不追求向商家销售最贵的方案，而是选择最符合当前发展阶段、能够带来可持续增长的方案。','A strong BD professional helps the merchant choose the growth strategy that best fits their current stage.'])}</blockquote><div className="final-close"><b>建议下一步</b><span>确认试点目标 → 准备菜单与图片 → 完成签约上线 → 按周复盘优化</span><strong>感谢聆听 · 欢迎提问</strong></div></div>}}
function Merchant({l}:{l:L}){const[a,setA]=useState(0),why=['抽成会直接影响每单剩余利润，必须先看订单是否为新增且仍有正向贡献。','堂食称重无法直接搬到线上，否则价格、分量和成本都难以控制。','漏汤或口感下降会影响评分、退款和复购，必须上线前测试。','高峰期插入外卖订单可能拖慢堂食与出餐，需按产能控制。','平台价值必须通过新增顾客和可衡量的增量订单来证明。'],action=['计算扣除抽成、食材、包装和人工后的单笔贡献利润','用固定分量套餐代替线上称重，并保留有限的自选项','测试密封汤碗、分装方案、配送半径和最佳食用时间','限定非高峰营业时段、设置备餐时间和订单上限','设定三个月试点，以新客、转化、利润和复购作为判断标准'];return <div><Title n={1} l={l}/><div className="two"><Card><div className="avatar">李</div><h2>{l==='zh'?'李先生':'Mr. Li'}</h2><p>{tx(l,['8年餐饮经验 · 首家自有品牌 · 主要决策者','8 years in restaurants · First owned brand · Key decision-maker'])}</p><div className="tags"><b>{tx(l,['价格敏感','Margin-aware'])}</b><b>{tx(l,['计划扩店','Expansion-minded'])}</b><b>{tx(l,['外卖新手','Delivery novice'])}</b></div></Card><div className="concerns">{concerns.map((x,i)=><Card key={i} onClick={()=>setA(i)} on={a===i}><b>{tx(l,x)}</b>{a===i&&<><p>{why[i]}</p><small>建议应对：{action[i]}</small></>}</Card>)}</div></div></div>}
function Process({l}:{l:L}){const[a,setA]=useState(0),it=['门店调研','建立信任','需求诊断','方案设计','处理异议','签约与跟进'],details=['了解商圈、客群、竞品、菜单、评价和门店当前经营状态。','认可李先生八年餐饮经验，说明来意并获得继续沟通的许可。','确认客单价、成本、忙闲时段、剩余产能、目标和成功标准。','围绕标准套餐、包装、营业时段、利润和平台方案形成建议。','先认可顾虑，再追问原因，用测算和可执行方案回应。','总结共识，确认三个月试点目标，明确签约、上线和复盘节点。'];return <div><Title n={2} l={l}/><div className="six">{it.map((x,i)=><Card key={x} onClick={()=>setA(i)} on={a===i}><em>0{i+1}</em><h3>{x}</h3>{a===i&&<p>{details[i]}</p>}</Card>)}</div><blockquote>{tx(l,['我不会先卖套餐，而是先确认饭团是否真的能帮助商家赚钱。','I would first determine how Fantuan can genuinely help the merchant grow.'])}</blockquote></div>}
function Opening({l}:{l:L}){const[step,setStep]=useState(0),[bad,setBad]=useState(false);const conversation=[
 {who:'Chris',text:'李老板您好，我是饭团的 Chris。谢谢您在开业这么忙的时候抽时间见我。先恭喜您终于把自己的麻辣烫品牌开起来了。'},
 {who:'李先生',text:'谢谢。最近确实挺忙的，你们主要是想让我上平台吧？'},
 {who:'Chris',text:'是的。简单介绍一下，饭团是连接本地消费者、餐厅和配送服务的生活服务平台。对商家来说，它不只是增加一个接单入口，还可以通过平台曝光、自取和配送，帮助门店接触原本覆盖不到的顾客。'},
 {who:'李先生',text:'那顾客下单以后，具体是怎么运作的？我这边需要做什么？'},
 {who:'Chris',text:'顾客在饭团上查看菜单、下单并付款；门店收到订单后确认、备餐和打包；配送订单由骑手取餐送达，自取订单由顾客到店领取。上线前，我们会一起整理菜单、图片、价格、营业时间和配送范围；上线后再根据订单、评价和出餐情况持续优化。'},
 {who:'Chris',text:'在具体谈方案和抽成之前，我想先了解您的经营重点。我了解到您做了八年餐饮，从后厨、成本到门店管理都很熟，而且以后还想在大温继续开店。这次自己做品牌，您最想先把哪件事做好？'},
 {who:'李先生',text:'第一家店还是要先稳住利润，也想看看这个品牌在不同区域有没有市场。'},
 {who:'Chris',text:'明白，所以重点不是单纯增加订单，而是增加有利润、后厨接得住的订单，同时为以后扩店积累数据。这样吧，我先用几分钟了解您的客单价、忙闲时段和产能，再判断饭团适不适合；如果不适合，我也会直接告诉您。可以吗？'}
 ];const reasons=['礼貌说明身份，尊重商家的时间，先建立正常的人际交流。','商家直接试探销售目的，此时不回避，也不急着报价。','用一句话说明饭团的角色，并把重点放在商家能够获得的价值。','鼓励商家提出实际操作问题，确认他最需要了解的内容。','清楚说明订单流转、双方分工和上线后的支持，降低未知感。','用事前调研肯定对方经验，再用开放式问题让商家先谈目标。','复述商家的原话，确认“利润＋扩店验证”才是真正需求。','总结共同目标、降低销售戒备，并获得继续提问的许可。'];const stageTitles=['礼貌破冰','回应商家试探','简要介绍饭团','了解操作疑问','说明合作如何运作','认可经历并提问','确认真实目标','获得访谈许可'];const focuses=['尊重商家时间，建立平等的沟通关系','坦诚说明来意，不回避合作目的','平台简介保持简短，先讲与商家相关的价值','让商家主动说出对运营流程的疑问','讲清顾客下单、门店备餐、配送或自取的完整流程','用事前调研建立信任，用开放式问题了解目标','准确倾听并复述，确认核心需求','降低戒备，在获得许可后进入需求访谈'];return <div><Title n={3} l={l}/><div className="two opening"><div className="chat">{conversation.slice(0,step+1).map((m,i)=><motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} key={i} className={'bubble '+(m.who==='Chris'?'me':'')}><b>{m.who}</b><p>{m.text}</p></motion.div>)}</div><Card><div className="profile-label">第 {step+1} 步 · 开场目的</div><h2>{stageTitles[step]}</h2><p>{reasons[step]}</p><hr/><h3>本步沟通重点</h3><p>{focuses[step]}</p>{bad&&<div className="bubble bad"><b>价格先行的开场方式</b><p>“李老板，我们有20%、25%和30%三档方案，VIP曝光最好，今天可以签吗？”</p><small>问题：还没了解经营目标就开始报价，容易让商家只关注抽成并产生防备。</small></div>}</Card></div><div className="actions"><button className="primary" onClick={()=>setStep(s=>Math.min(conversation.length-1,s+1))}>{step<conversation.length-1?'继续对话':'已进入需求访谈'}</button><button onClick={()=>{setStep(0);setBad(false)}}>从头查看</button><button onClick={()=>setBad(!bad)}>{bad?'隐藏价格先行风险':'对比价格先行方式'}</button></div></div>}
function Discovery({l}:{l:L}){const[p,setP]=useState('利润优先'),[c,setC]=useState('适中'),[e,setE]=useState('无经验');return <div><Title n={4} l={l}/><div className="two"><div className="questions">{['经营现状','客单价与利润','产品与顾客','时段与产能','目标与成功标准'].map((x,i)=><Card key={x}><b>0{i+1} · {x}</b><p>{['目前以堂食为主吗？是否已有自取或外卖？现在如何称重计价？','平均客单价多少？食材、包装和人工成本如何？每单最低要留下多少利润？','哪些汤底和食材最受欢迎？主要顾客是学生、上班族、家庭还是夜宵客群？','高峰和非高峰分别在什么时候？后厨每天还能稳定承接多少外卖订单？','更看重新客、非高峰收入还是扩店验证？三个月后什么结果代表合作成功？'][i]}</p></Card>)}</div><Card><Choice label="首要目标" value={p} set={setP} items={['利润优先','曝光优先','扩店验证']}/><Choice label="后厨剩余产能" value={c} set={setC} items={['有限','适中','充足']}/><Choice label="外卖经验" value={e} set={setE} items={['无经验','有一些','经验丰富']}/><hr/><div className="profile-label">动态商家画像</div><h2>{merchantProfile(p,c,e).type}</h2><p>{merchantProfile(p,c,e).summary}</p><div className="profile-risk">{merchantProfile(p,c,e).risk}</div><div className="profile-plan">{merchantProfile(p,c,e).plan}</div></Card></div></div>}
function Combo({l}:{l:L}){const[b,setB]=useState(16.9),[add,setAdd]=useState('不选'),[drink,set饮料]=useState('不选');return <div><Title n={5} l={l}/><div className="transform">自选 → 称重 → 汤底　<ArrowRight/>　<b>标准套餐 → 汤底 → 辣度 → 加购 → 配送</b></div><div className="two"><div className="menu">{[['经典单人',16.9],['高蛋白牛肉',20.9],['素菜套餐',15.9],['双人分享',32.9],['家庭套餐',49.9],['夜宵套餐',18.9]].map(x=><Card key={x[0]} onClick={()=>setB(x[1] as number)} on={b===x[1]}><b>{x[0]}</b><h3>${x[1]}</h3></Card>)}</div><Card><h2>搭配一份外卖套餐</h2><Choice label="高利润加购" value={add} set={setAdd} items={['不选','肥牛 +$4']}/><Choice label="饮料选择" value={drink} set={set饮料} items={['不选','饮料 +$2.5']}/><div className="result">${(b+(add==='不选'?0:4)+(drink==='不选'?0:2.5)).toFixed(2)}</div><small>{tx(l,['示例假设价格','Sample assumptions'])}</small></Card></div></div>}
function Values({l}:{l:L}){return <div><Title n={6} l={l}/><p className="lead">先用公开数据说明平台能力，再用同品类情景测算展示合作逻辑。</p><div className="three evidence"><Card><small>平台官网公开数据</small><div className="metric">359万+</div><h3>平台用户</h3><p>说明饭团具备触达大量线上消费者的基础。</p></Card><Card><small>平台官网公开数据</small><div className="metric">7.49万+</div><h3>合作商家</h3><p>说明平台已积累大规模商家合作与上线经验。</p></Card><Card><small>平台官网公开数据</small><div className="metric">7.99万+</div><h3>配送伙伴</h3><p>说明平台具备支持配送履约的网络基础。</p></Card></div><div className="two evidence-notes"><Card><div className="profile-label">公开运营案例 · 美国业务</div><h2>平台履约能力得到规模化验证</h2><p>DoorDash公开案例显示，Fantuan接入其按需配送服务后，周订单量增长至原来的5倍、美国业务增长50%、配送成本下降20%。其中周订单比较口径为2023年第一季度与2024年第一季度。</p><a href="https://merchants.doordash.com/en-us/success-stories/fantuan" target="_blank" rel="noreferrer">查看公开案例来源</a></Card><Card><div className="profile-label">同品类模拟 · 新开麻辣烫店</div><h2>把称重堂食改造成可控的外卖试点</h2><p><b>改造：</b>上线6个固定分量套餐，保留汤底、辣度和加购；先在非高峰开放，使用密封汤碗并设置订单上限。</p><div className="scenario-metrics"><span>客单价 <b>$27</b></span><span>日均新增 <b>12单</b></span><span>单笔贡献 <b>$8.95</b></span><span>月度贡献 <b>$2,792</b></span></div><small>测算：$27×(1−25%)−食材$8.10−包装$1.20−增量人工$2.00＝$8.95/单；$8.95×12单×26天＝$2,792。</small></Card></div><p className="legal">平台规模与美国业务案例来自公开网页；麻辣烫案例为情景模拟，所有价格、订单和利润均为示例假设，不代表真实商家表现或平台保证。</p></div>}
function Packages({l}:{l:L}){return <div><Title n={8} l={l}/><div className="three">{[['20%','经济方案','基础排序展示 · 基础配送'],['25%','VIP方案','额外曝光 · 活动支持 · 宣传物料'],['30%','至尊方案','稳定高等级曝光 · 更高力度支持']].map((x,i)=><Card key={x[0]} on={i===1}>{i===1&&<mark>推荐方案</mark>}<h2>{x[1]}</h2><div className="result">{x[0]}</div><p>{x[2]}</p><small>{['成熟商家 / 低成本优先','新品牌 / 平衡成本与增长','激进增长 / 产能成熟'][i]}</small></Card>)}</div><p className="legal">{tx(l,['具体权益、费用和平台规则以饭团正式合同及当前政策为准。','Final benefits, commission terms and policies are subject to Fantuan’s official agreement and current policies.'])}</p></div>}
function Recommend({l}:{l:L}){const[sel,setSel]=useState(['建立知名度','测试需求']),it=['降低成本','建立知名度','增加订单','测试需求','多店扩张','保护产能'];const r=sel.includes('降低成本')&&sel.length<3?'20% 经济方案':sel.length>4?'30% 至尊方案':'25% VIP方案',isEconomy=r.startsWith('20'),isPremium=r.startsWith('30'),reason=isEconomy?'当前选择明显偏向降低成本，且对额外曝光和增长支持需求较低；经济方案更适合已有稳定客源、以控制抽成为主的商家。':isPremium?'当前选择同时强调订单、曝光和多店扩张，且需要较强投入；至尊方案适合产能成熟、愿意承担更高成本以加速增长的商家。':'李先生是新品牌，需要曝光和新客，也要控制初期成本与后厨压力；VIP方案在增长支持和经营风险之间更平衡。',statement=isEconomy?'选择经济方案的前提，是商家已经有稳定需求，不依赖平台额外曝光。':isPremium?'选择至尊方案的前提，是后厨产能和单笔利润已经得到验证。':'推荐VIP方案，不是因为抽成更高，而是因为它更符合李先生当前的发展阶段。';return <div><Title n={9} l={l}/><div className="two recommend"><div>{it.map(x=><button className={sel.includes(x)?'picked':''} onClick={()=>setSel(s=>s.includes(x)?s.filter(y=>y!==x):[...s,x])}>{x}</button>)}</div><Card><small>根据所选优先级</small><div className="result">{r}</div><p>{reason}</p></Card></div><blockquote>{statement}</blockquote></div>}
function Calc({l}:{l:L}){const[a,setA]=useState(24),[food,setFood]=useState(30),[comm,setComm]=useState(25),[orders,set订单量]=useState(15);const c=a*(1-comm/100)-a*food/100-1.2-2,m=c*orders*26;return <div><Title n={7} l={l}/><div className="two calc"><div>{[['平均客单价',a,setA,12,50],['食材成本率 %',food,setFood,15,50],['平台抽成 %',comm,setComm,20,30],['预计饭团日均新增订单（单/天）',orders,set订单量,1,60]].map(([x,v,s,min,max]:any)=><label>{x}<b>{x==='预计饭团日均新增订单（单/天）'?v+' 单':x.includes('%')?v+'%':'$'+v}</b><input type="range" value={v} min={min} max={max} onChange={e=>s(+e.target.value)}/></label>)}</div><Card><small>预计单笔贡献利润</small><div className="result">${c.toFixed(2)}</div><small>预计月度增量贡献利润</small><div className="result teal">${m.toFixed(0)}</div><p>{tx(l,['以上为基于示例假设的简化测算，不代表平台承诺。按每月营业26天计算，未计入房租等固定成本、税费、活动补贴、退款及其他费用。','Simplified estimate, not guaranteed. Excludes fixed costs, tax, promotions and refunds.'])}</p></Card></div></div>}
function Objections({l}:{l:L}){const[a,setA]=useState(0),[show,setShow]=useState(false);return <div><Title n={10} l={l}/><div className="two objection"><div>{obj.map((x,i)=><button className={a===i?'picked':''} onClick={()=>{setA(i);setShow(false)}}>{x[l==='zh'?0:1]}</button>)}</div><Card><h2>“{obj[a][l==='zh'?0:1]}”</h2>{show?<><p>{obj[a][l==='zh'?2:3]}</p><small>✓ 认可顾虑　✓ 追问原因　✓ 解释价值　✓ 提供方案　✓ 推动下一步</small></>:<button className="primary" onClick={()=>setShow(true)}>{tx(l,['显示建议回答','Reveal Suggested Answer'])}</button>}</Card></div></div>}
function Growth({l}:{l:L}){const[a,setA]=useState(0),it=['新客获取','菜单优化','提高客单价','利用非高峰','发展自取','评价与复购'],actions=['利用新店曝光、清晰品类标签和合适活动，触达熟悉亚洲餐饮及麻辣烫的本地顾客。','将菜单精简为4–6个核心套餐，使用清晰图片，说明分量、汤底、辣度和主要食材。','在主套餐后提供肥牛、午餐肉、丸类、主食、饮料和小吃等高毛利加购。','优先开放下午、工作日晚间和夜宵时段，并根据后厨表现逐步延长营业时间。','面向附近顾客设置自取选择，减少配送等待，并创造未来到店消费机会。','稳定包装、口味和出餐时间，主动复盘差评原因，提升复购和评分。'],impact=['扩大品牌触达，增加原本没有接触到门店的新客。','降低顾客决策难度和错单率，同时提高页面转化。','在不依赖更大折扣的情况下提高客单价和贡献利润。','把闲置产能转化为增量收入，避免冲击堂食高峰。','增加一个成本更可控的订单来源，并扩大门店附近客群。','降低退款和投诉，形成更稳定的长期订单。'],kpi=['新客订单数与列表曝光量','菜单浏览转化率与错单率','平均客单价与加购率','分时段订单量与平均备餐时间','自取订单占比与到店转化','顾客评分、投诉率与复购率'];return <div><Title n={11} l={l}/><div className="two growth"><div>{it.map((x,i)=><button className={a===i?'picked':''} onClick={()=>setA(i)}>{i+1}<span>{x}</span></button>)}</div><Card><small>建议动作</small><h2>{it[a]}</h2><p>{actions[a]}</p><hr/><b>预期作用</b><p>{impact[a]}</p><b>衡量指标 → {kpi[a]}</b></Card></div></div>}
function Timeline({l}:{l:L}){return <div><Title n={12} l={l}/><div className="four timeline">{[['第1–2周','设置与验证','确定套餐、测试包装、准备图片、设置营业时间'],['第3–4周','小范围上线','控制订单量、记录备餐时间、解决包装与出品问题'],['第2个月','增长优化','测试合适的活动、加购、双人套餐和自取需求'],['第3个月','复盘与扩张','复盘订单量、客单价、贡献利润、评价和订单区域']].map((x,i)=><Card><em>0{i+1} · {x[0]}</em><h2>{x[1]}</h2><p>{l==='zh'?x[2]:'Validate, launch carefully, optimize and decide how to scale.'}</p></Card>)}</div></div>}
function Dashboard({l}:{l:L}){const[p,setP]=useState(1),d=[[1200,42,3.5,26],[4600,210,4.6,27],[14800,790,5.3,29]][p];return <div><Title n={13} l={l}/><div className="tabs">{['第1周','第1个月','第3个月'].map((x,i)=><button className={p===i?'picked':''} onClick={()=>setP(i)}>{x}</button>)}</div><div className="four dashboard">{[['列表曝光量',d[0]],['订单量',d[1]],['下单转化率',d[2]+'%'],['平均客单价','$'+d[3]],['顾客评分','4.8 / 5'],['平均备餐时间','18分钟'],['复购率','22%'],['投诉率','1.2%']].map(x=><Card><small>{x[0]}</small><div className="metric">{x[1]}</div><b>示例数据</b></Card>)}</div></div>}
function Closing({l,go}:{l:L;go:(x:number)=>void}){return <div><Title n={14} l={l}/><div className="two close-sale"><Card><h3>{tx(l,['商家目标','Merchant Goals'])}</h3><p>获取新客 · 利用非高峰产能 · 保护利润 · 为扩店验证市场</p><h3>{tx(l,['建议方案','Recommended Solution'])}</h3><p>标准化外卖菜单 · 25% VIP方案 · 三个月可控试点 · 按数据持续优化</p></Card><Card><p>{tx(l,['李老板，我建议从VIP方案和标准化外卖套餐开始，设定三个月测试目标。如果您认可，下一步准备菜单、图片和营业时间。您觉得怎么样？','Mr. Li, I recommend VIP, a standardized menu and a three-month pilot. If this makes sense, our next step is to prepare the menu, photos and hours. How does that sound?'])}</p><button className="primary">{tx(l,['我愿意推进','Proceed to Onboarding'])}</button><button onClick={()=>go(9)}>{tx(l,['我还要考虑抽成','Return to Profit Calculator'])}</button><button onClick={()=>go(12)}>{tx(l,['了解运营细节','View 90-Day Plan'])}</button></Card></div></div>}
